# update_frequency: 地图更新频率
# publish_frequency: 地图可视化发布频率
# static_map: 是否有预先生成好的地图用于初始化
# rolling_window: 在机器人移动时是否滚动窗口, 以保证机器人始终处于地图中央
# width: 地图宽度
# height: 地图高度
# resolution: 地图分辨率
# transform_tolerance: move_base中允许出现的传感器的最大误差
# map_type: 地图类型, 是cost_map

local_costmap:
   global_frame: world
   robot_base_frame: base
   update_frequency: 5.0
   publish_frequency: 3.0
   static_map: false
   rolling_window: true
   width: 5.0
   height: 5.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap